### PR TITLE
NVRAM v3 format support, refactoring

### PR DESCRIPTION
**Pull request by nohajc**
A new format is used for NVRAM variables on some Apple Silicon machines. I haven't verified this but it could also correspond to iBoot version (and/or macOS version) including the reported NVRAM size which recently changed rom 128 kB to 1 MB (as discussed in https://github.com/AsahiLinux/linux/issues/193).

Anyway, I split the code into two NVRAM implementations (v3 and v1v2) while also changing the API a little bit in order to abstract the format differences.

The original implementation still assumes 2 NVRAM banks (128 kB) and probably needs further adjustments to support both v1 and v2 (which are [very similar](https://github.com/apple-oss-distributions/xnu/blob/main/iokit/Kernel/IONVRAMCHRPHandler.cpp#L32) though).

One thing I noticed when toggling boot volume repeatedly (via macOS System Settings) is that the NVRAM generation does not change on every update (or even reboot). Instead, the state flag of modified variables is changed from 0x7F to 0x7C (curiously not found anywhere in the published Apple source code) and a new copy with updated value is appended to the NVRAM partition. I assume this happens until the bank is full and only after that it will increment the generation counter and use the next bank.

I din't want to complicate things so I just used in-place modification instead. I see no reason why it wouldn't work but I haven't tried it yet on my real machine. Last time I tried with a macOS VM (just to check what is inside the emulated NVRAM) it was still the old format.

### CODE REVIEW

**Comment by WhatAmISupposedToPutHere** [comment]
I would strongly prefer if this was tested on a real device and not done in-place writes. I do not think that the flash chip does wear leveling, so rotating banks seems to be a good thing for it's longevity.

**Comment by WhatAmISupposedToPutHere** [comment]
Also, that 0x7C is just VAR_ADDED & VAR_IN_DELETED_TRANSITION & VAR_DELETED, they seem to do it this way since you can only go 1 -> 0 on nvram w/o erasing it

**Comment by nohajc** [comment]
> I would strongly prefer if this was tested on a real device and not done in-place writes. I do not think that the flash chip does wear leveling, so rotating banks seems to be a good thing for it's longevity.

I can change it but I still don't understand 100% how it's supposed to work. If macOS modifies the flag from 0x7F to 0x7C and then still writes the new value to the same bank, doesn't that require overwriting the whole bank anyway?

I'd understand if it used the next bank for every update which is what asahi-nvram already does for the old format. So I'm inclined to do the same here even though it's not equivalent to the official solution.

Regarding the test, I would definitely do it, except my only device is also my daily driver so I'm a little nervous about it.

**Comment by nohajc** [comment]
Oh, I think I get it now. The padding bytes are `0xFF` so you're saying this makes it possible to update values without even calling the erase ioctl. That is until we run out of banks and start from bank 0 again. That's clever.

**Comment by WhatAmISupposedToPutHere** [comment]
> > I would strongly prefer if this was tested on a real device and not done in-place writes. I do not think that the flash chip does wear leveling, so rotating banks seems to be a good thing for it's longevity.
> 
> I can change it but I still don't understand 100% how it's supposed to work. If macOS modifies the flag from 0x7F to 0x7C and then still writes the new value to the same bank, doesn't that require overwriting the whole bank anyway?

If you overwrite the data without erasing it first, only the zero values get written. And it is the erase part that is hard on the cells, writes are not as damaging.

> I'd understand if it used the next bank for every update which is what asahi-nvram already does for the old format. So I'm inclined to do the same here even though it's not equivalent to the official solution.

Yes, that would be a perfectly fine solution, as long as the banks are rotated, the wear is spread across the cells.

> Regarding the test, I would definitely do it, except my only device is also my daily driver so I'm a little nervous about it.

Well, thats the reason i am not merging it w/o testing. Anyway, i had destroyed the entire contents of the nvram area while developing this, and the only thing that happened was that the machine booted into the boot picker, and the boot chime volume was set to max. So you _should_ be fine (no warranty tho :P)

**Comment by nohajc** [comment]
> Well, thats the reason i am not merging it w/o testing.
I meant somebody else could test it for me (😉).

Anyway, thanks for the quick response, I'll work on the PR and let you know when it's ready.

**Comment by nohajc** [comment]
Oh, one more thing. Am I right that the `erase_if_needed` ioctl is a no-op if the bank is already empty/erased?

**Comment by WhatAmISupposedToPutHere** [comment]
> I meant somebody else could test it for me (😉).
My machines are M1 MBP, and M1Pro MBP, both of those use the old format. I would be much more inclined to just grab the code as-is and fix it up myself if i could test it,

**Comment by WhatAmISupposedToPutHere** [comment]
> Oh, one more thing. Am I right that the `erase_if_needed` ioctl is a no-op if the bank is already empty/erased?

It will issue another erase command, possibly stressing the cells again. the if_needed part refers to the fact that you can direct this tool to a regular file containing a nvram dump for testing purposes, and it will not try to issue erases on something that isn't a mtd device

**Comment by nohajc** [comment]
Ok, makes sense, I'll avoid calling it unless needed. Thanks.

**Comment by nohajc** [comment]
@WhatAmISupposedToPutHere I'm ready for code review. My testing was successful.

Ultimately, I decided to implement it including the variable invalidation scheme. That is, change state from 7F to 7C, append a new copy of the variable with updated value unless the bank is full or we encounter anything other than FF bytes.

First, I tried simple variable update within the same bank, then I also forced it to erase the first bank (pretending I've got fewer banks than 16 because otherwise it would take very long - I don't call erase if I detect a fully empty bank). Not only I didn't brick my machine, it also did exactly what I wanted.

**Comment by WhatAmISupposedToPutHere** [comment]
Have you checked updates with bank overflow? If yes, i will test it on my machines that use v1, and merge it in a bit.

**Comment by nohajc** [comment]
> Have you checked updates with bank overflow? If yes, i will test it on my machines that use v1, and merge it in a bit.

Yes, I did. I was able to recreate the variables both in an empty bank and a previously used one after erase.

**Comment by WhatAmISupposedToPutHere** [comment]
Merged manually.

Instead of asking you to make changes and then waiting - just did them myself, so posting the summary:
1. Don't leave commented out code in files.
2. Made the nvram read command function the same in v1v2 and v3, it is supposed to output the entire variable's content and be script-parseable

Also, turns out my m1pro mbp is using v3, so i could test that and confirming that at least bless works correctly.

**Comment by nohajc** [comment]
Thanks. I'm happy I could contribute. Also hoping I didn't break anything in the v1 implementation.

**Pull request closed without merging**
